baseURL = "https://morkerfyr.netlify.app"
languageCode = "ru"
title = "Mörkerfyr"

[menu]
  [[menu.nav]]
    name = "Радио"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Ревью"
    url = "/reviews/"
    weight = 2
  [[menu.nav]]
    name = "Подборки"
    url = "/collections/"
    weight = 3
  [[menu.nav]]
    name = "Галерея"
    url = "/gallery/"
    weight = 4

[params]
  images = ["img/logo-512.png"]
  audio = ["https://radio.morkerfyr.mle.party:8443/stream"]

  [[params.footer.authors]]
    name = "Fuerlee"
    description = "музыка, материалы"
    link = "https://t.me/fuerlee"
    weight = 1
  [[params.footer.authors]]
    name = "Sasha Wasilewska"
    description = "разработка, редактура"
    link = "https://innereq.org/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D1%86%D0%B0:Commagray"
    weight = 2 
  [[params.footer.authors]]
    name = "doesnm"
    description = "восстановление, разработка"
    link = "https://doesnm.cc"
    weight = 3
  [[params.footer.links]]
    name = "Telegram"
    link = "https://t.me/morkerfyr"
    weight = 1
  [[params.footer.links]]
    name = "ВКонтакте"
    link = "https://vk.com/morkerfyr"
    weight = 2
  [[params.footer.links]]
    name = "GitHub"
    link = "https://github.com/doesnmisclown/morkerfyr"
    weight = 3

[module]
[[module.imports]]
  path = 'github.com/hugo-mods/icons'
