backend:
  name: 'git-gateway'
  branch: 'master'
media_folder: 'static/img'
public_folder: '/img'
collections:
  - name: 'reviews'
    label: 'Ревью'
    folder: 'content/reviews'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'collections'
    label: 'Подборки'
    folder: 'content/collections'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'releases'
    label: 'Релизы'
    folder: 'content/releases'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Album', name: 'album', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Spotify', name: 'spotify', widget: 'string', required: false }
      - { label: 'Bandcamp', name: 'bandcamp', widget: 'string', required: false }
      - { label: 'Музыка ВКонтакте', name: 'vk', widget: 'string', required: false }
      - { label: 'Яндекс.Музыка', name: 'yandex', widget: 'string', required: false }

  - name: 'gallery'
    label: 'Галерея'
    folder: 'content/gallery'
    media_folder: 'static/img/gallery'
    public_folder: '/img/gallery'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Author'
        name: 'artist'
        widget: 'string'
      - label: 'Images'
        name: 'images'
        widget: 'image'
        media_library:
          config:
            multiple: true