name: "Build and Deploy"

on: push

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Install Node toolchain"
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: "Build frontend code"
        run: |
          yarn
          yarn export

      - name: "Deploy to GitHub Pages" 
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: __sapper__/export
          CLEAN: true