name: "Build and Deploy"

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Install Node toolchain"
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: "Build frontend code"
        run: |
          yarn
          yarn export

      - name: "Prepare build for deploying"
        run: |
          mv __sapper__/export morkerfyr.mle.party

      - name: "Deploy to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CI_DEPLOYER_SSH_ADDRESS_INNEREQ }}
          username: ${{ secrets.CI_DEPLOYER_SSH_USER }}
          key: ${{ secrets.CI_DEPLOYER_SSH_KEY_INNEREQ }}
          port: ${{ secrets.CI_DEPLOYER_SSH_PORT }}
          source: morkerfyr.mle.party
          target: /srv/http/morkerfyr.mle.party
          strip_components: 1
          rm: true
