name: "Backup GitHub issues using git-bug"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo curl -o /usr/local/bin/git-bug -L https://github.com/MichaelMure/git-bug/releases/download/0.7.1/git-bug_linux_amd64 \
          && sudo chmod +x /usr/local/bin/git-bug \
          && git config --local user.email "action@github.com" \
          && git config --local user.name "GitHub Action" \
          && git bug pull \
          && git bug bridge configure --name=default --target=github --owner=innereq --project=morkerfyr --token="${{ secrets.GITHUB_TOKEN }}" \
          && git bug bridge pull \
          && git bug push